parameters:

services:
    data_collector.leek_git_debug:
        class: Leek\GitDebugBundle\DataCollector\GitDataCollector
        arguments: ["%%kernel.root_dir%"]
        tags:
            - { name: data_collector, template: "LeekGitDebugBundle:Collector:gitdebug", id: "leek_git_debug" }